@startuml classes
set namespaceSeparator none
class "Sessions" as core.session.Sessions #aliceblue {
  sessions : dict
  add_new_session(username: str, db: Database) -> None
  get_all_sessions() -> dict
  get_session(username: str) -> UserSession
  remove_session(username: str) -> None
}
class "UserSession" as core.session.UserSession #aliceblue {
  cart : dict
  date : datetime, NoneType
  db : Database
  total_cost : int
  username : str
  add_new_item(id: int, name: str, price: int, quantity: int, discount: float, tax_rate: float) -> None
  empty_cart() -> dict
  is_item_in_cart(id: int) -> bool
  remove_item(id: int) -> None
  submit_cart() -> None
  update_item_quantity(id: int, change_to_quantity: int) -> None
  update_total_cost() -> None
  reset_user_password(old_password: str, new_password: str) -> bool
  set_user_password(new_password) -> None
}

class "AdminSession" as core.session.AdminSession #aliceblue {
  db : Database
  username: str
  date: datetime, NoneType
  add_new_product(self, name: str, price: int, info: str) -> None  remove_product(id: int) -> None
  update_product_inventory(id: int, inventory: int) -> None
  view_user_list() -> Database
  sales_report(start_date: datetime, end_date: datetime) -> Database
}

@enduml
